[package]
edition = "2021"
name = "prover-test-utils"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
strata-bridge-proof-primitives.workspace = true
strata-params.workspace = true
strata-primitives.workspace = true

bincode.workspace = true
bitcoin.workspace = true
borsh.workspace = true
serde_json.workspace = true
