[package]
edition = "2021"
name = "p2p-wire"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
bitcoin.workspace = true
libp2p.workspace = true
p2p-types.workspace = true
rkyv.workspace = true
