[package]
edition = "2021"
name = "strata-bridge-p2p-wire"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
strata-bridge-p2p-types.workspace = true

bitcoin.workspace = true
libp2p.workspace = true
rkyv.workspace = true
