exclude = ["target/**/*.toml", "functional-tests/_dd/**/*.toml"]

[formatting]
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["workspace.dependencies", "dependencies"]

[rule.formatting]
indent_string = "  "
reorder_keys = true
