[package]
name = "btc-tracker"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
algebra.workspace = true
strata-bridge-primitives = { workspace = true, features = ["async"] }

async-trait.workspace = true
bitcoin.workspace = true
bitcoincore-zmq = { version = "1.5.2", features = ["async"] }
bitcoind-async-client.workspace = true
futures.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "sync", "test-util"] }
tokio-stream.workspace = true
tracing.workspace = true


[dev-dependencies]
strata-bridge-common.workspace = true
strata-bridge-test-utils.workspace = true

corepc-node.workspace = true
proptest.workspace = true
serial_test.workspace = true
