network = "regtest"
genesis_height = 101

[keys]
musig2 = ["ac407ba319846e25d69c1c0cb2a845ab75ef93ad2e9e846cdc5cf6da766e00b2"]
p2p = ["0242f6ae559d2dc46b83fc820e9ba32f6ac8c387daac77f2805e930e924e3a127d"]

[tx_graph]
tag = "alpn"
deposit_amount = 1_000_000_000
operator_fee = 10_000_000
challenge_cost = 10_000_000
refund_delay = 1008

[stake_chain]
stake_amount = 100_000_000
burn_amount = 10_000_000
delta = { Blocks = 6 }
slash_stake_count = 24

[connectors]
payout_optimistic_timelock = 1_008
pre_assert_timelock = 1_152
payout_timelock = 1_008

[sidesystem]
deposit_amount = 1_000_000_000
operator_config.static = [
  { signing_pk = "0x8d86834e6fdb45ba6b7ffd067a27b9e1d67778047581d7ef757ed9e0fa474000", wallet_pk = "0xac407ba319846e25d69c1c0cb2a845ab75ef93ad2e9e846cdc5cf6da766e00b2" },
]

magic_bytes = [65, 76, 80, 78]
block_time = 1_000
da_tag = "alpen-bridge-da"
checkpoint_tag = "alpen-bridge-checkpoint"
cred_rule = "unchecked"
horizon_l1_height = 1_000
genesis_l1_height = 1_000
l1_reorg_safe_depth = 1_000
target_l2_batch_size = 1_000
max_address_length = 20
dispatch_assignment_dur = 1000
proof_publish_mode = "strict"
checkpoint_predicate = "AlwaysAccept"
max_deposits_in_block = 20
network = "signet"
evm_genesis_block_hash = "0x46c0dc60fb131be4ccc55306a345fcc20e44233324950f978ba5f185aa2af4dc"
evm_genesis_block_state_root = "0x351714af72d74259f45cd7eab0b04527cd40e74836a45abcae50f92d919d988f"
rollup_vk.native = "0x0000000000000000000000000000000000000000000000000000000000000000"

[sidesystem.genesis_l1_view]
next_target = 545259519
epoch_start_timestamp = 1296688602
last_11_timestamps = [
  1764086031,
  1764086031,
  1764086032,
  1764086032,
  1764086032,
  1764086032,
  1764086032,
  1764086032,
  1764086033,
  1764086033,
  1764086033,
]

[sidesystem.genesis_l1_view.blk]
height = 100
blkid = "f2c22acbe3b24e429349296b958c40b692356436086750bd7564ebfceb915100"
