[package]
name = "strata-bridge-sm"
version = "0.1.0"
edition = "2024"
description = "State machines for the Strata Bridge"

[lints]
workspace = true

[dependencies]
strata-bridge-connectors2.workspace = true
strata-bridge-primitives.workspace = true
strata-bridge-tx-graph2.workspace = true

strata-asm-common.workspace = true
strata-asm-txs-bridge-v1.workspace = true
strata-l1-txfmt.workspace = true

bitcoin.workspace = true
bitcoin-bosd.workspace = true
musig2.workspace = true
serde.workspace = true
thiserror.workspace = true
zkaleido.workspace = true

[dev-dependencies]
strata-bridge-test-utils.workspace = true
strata-bridge-p2p-types.workspace = true

strata-l1-txfmt.workspace = true

musig2.workspace = true
proptest.workspace = true
secp256k1.workspace = true
