[package]
edition = "2021"
name = "strata-bridge-tx-graph2"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
strata-asm-txs-bridge-v1.workspace = true
strata-bridge-connectors2.workspace = true
strata-bridge-primitives.workspace = true
strata-l1-txfmt.workspace = true
strata-primitives.workspace = true

algebra.workspace = true
bitcoin = { workspace = true, features = ["rand-std"] }
bitcoin-bosd = { workspace = true, features = ["address"] }
futures.workspace = true
secp256k1 = { workspace = true, features = ["global-context", "rand-std"] }
serde.workspace = true

[dev-dependencies]
strata-bridge-test-utils.workspace = true
strata-bridge-connectors2 = { workspace = true, features = ["test_utils"] }

tokio = { workspace = true, features = ["rt", "macros"] }
