seed = "/Users/abishekbashyal/Codes/strata-bridge/functional-tests/config/s2_seed"
network = "regtest"

[tls]
key = "/Users/abishekbashyal/Codes/strata-bridge/functional-tests/config/s2/tls/key.pem"
cert = "/Users/abishekbashyal/Codes/strata-bridge/functional-tests/config/s2/tls/cert.pem"
ca = "/Users/abishekbashyal/Codes/strata-bridge/functional-tests/config/s2/tls/bridge.ca.pem"

[transport]
addr = "0.0.0.0:69"
