seed = "/Users/abishekbashyal/Desktop/temp/seed"
network = "regtest"

[tls]
key = "/Users/abishekbashyal/Desktop/temp/s2/tls/key.pem"
cert = "/Users/abishekbashyal/Desktop/temp/s2/tls/cert.pem"
ca = "/Users/abishekbashyal/Desktop/temp/s2/tls/bridge.ca.pem"

[transport]
addr = "0.0.0.0:69"
