[package]
name = "strata-bridge-db2"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-bridge-primitives.workspace = true
strata-bridge-sm.workspace = true

bitcoin = { workspace = true, features = ["rand-std"] }
foundationdb = { workspace = true, optional = true }
postcard.workspace = true
secp256k1 = { workspace = true, features = ["global-context", "rand-std"] }
serde = { workspace = true, optional = true, features = ["derive"] }
terrors.workspace = true

[lints]
workspace = true

[features]
default = ["fdb"]
fdb = ["foundationdb", "serde"]

[dev-dependencies]
strata-bridge-test-utils.workspace = true
strata-bridge-tx-graph2.workspace = true

proptest.workspace = true
tokio.workspace = true
